name: Deploy to server
on: push


jobs:
  first_job:
    runs-on: ubuntu-latest

    steps: 

    - name: Hola Mundo
      run: echo "hola mundos"
  second_job:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: first_job
    runs-on: ubuntu-latest

    steps: 

    - name: Hola MUndo
      run: echo "hola mundo22"
